char *alloc(int nbytes);
int alpha(char c);
int alphan(char c);
void any(char c,char *str);
void cross(struct nlist *point);
int delim(char c);
void error(char *str);
void errors(char *msg, char *str);
void emit(char byte);
void eword(int wd);
void fwdinit(void);
void fwdmark(void);
void fwdnext(void);
void fwdreinit(void);
void f_record(void);
void fatal(char *str);
int head( char *str1, char *str2 );
void hexout(int byte);
int hibyte(int i);
void initialize(void);
int lobyte(int i);
void localinit(void);
void make_pass(void);
char mapdn(char c);
void open_files(void);
int parse_line(void);
void print_line(void);
void process(void);
void re_init(void);
char *skip_white(char *ptr);
void stable(struct nlist *ptr);
void warn(char *str);
char white(char c);
