
void abd_index(int pbyte);
char *alloc(int nbytes);
int alpha(char c);
int alphan(char c);
int any(char c,char *str);
void binout(int byte);
void cross(struct nlist *point);
int delim(char c);
void do_gen(int op, int mode);
void do_indexed(int op);
void do_op(int opcode, int class);
void do_pseudo(int op);
void error(char *str);
void errors(char *msg, char *str);
int emit(char byte);
int eval(void);
void eword(int wd);
void fwdinit(void);
void fwdmark(void);
void fwdnext(void);
void fwdreinit(void);
void f_record(void);
void fatal(char *str);
int get_term(void);
int head( char *str1, char *str2 );
void hexout(int byte);
int hibyte(int i);
void initialize(void);
int install(char *str, int val);
int is_op(char c);
int lobyte(int i);
void localinit(void);
struct nlist *lookup(char *name);
void make_pass(void);
char mapdn(char c);
struct oper *mne_look(char *str);
void open_files(void);
int parse_line(void);
void print_line(void);
void process(void);
void re_init(void);
int regnum(void);
int rtype(int r);
int set_mode(void);
char *skip_white(char *ptr);
void stable(struct nlist *ptr);
void warn(char *str);
char white(char c);
